# Generated by Django 5.0.3 on 2026-02-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('bulletin', 'Flood Risk Bulletin'), ('situation', 'Situation Report'), ('ai_brief', 'AI Briefing Summary')], default='bulletin', max_length=20),
        ),
    ]
