# Generated by Django 5.0.3 on 2026-03-16 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_aichatmessage_airequestlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('email', 'Email')], default='sms', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcast_recipients', to='api.county')),
                ('sub_county', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.subcounty')),
            ],
            options={
                'ordering': ['county', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CameraFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('location_label', models.CharField(blank=True, max_length=200)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('stream_url', models.URLField(max_length=500)),
                ('feed_type', models.CharField(choices=[('cctv', 'CCTV'), ('drone', 'Drone'), ('satellite', 'Satellite'), ('weather', 'Weather Station'), ('river', 'River Gauge Camera')], default='cctv', max_length=20)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('degraded', 'Degraded')], default='offline', max_length=20)),
                ('is_public', models.BooleanField(default=False)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to='api.county')),
            ],
            options={
                'ordering': ['county', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('incident_type', models.CharField(choices=[('flood', 'Flood'), ('drought', 'Drought'), ('landslide', 'Landslide'), ('infrastructure', 'Infrastructure Damage'), ('displacement', 'Mass Displacement'), ('other', 'Other')], default='flood', max_length=30)),
                ('status', models.CharField(choices=[('open', 'Open'), ('active', 'Active'), ('contained', 'Contained'), ('closed', 'Closed')], default='open', max_length=20)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('affected_population', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_incidents', to=settings.AUTH_USER_MODEL)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='api.county')),
                ('opened_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opened_incidents', to=settings.AUTH_USER_MODEL)),
                ('sub_county', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='api.subcounty')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FieldUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unit_type', models.CharField(choices=[('vehicle', 'Vehicle'), ('boat', 'Boat'), ('drone', 'Drone'), ('foot', 'Foot Patrol'), ('helicopter', 'Helicopter')], default='vehicle', max_length=20)),
                ('current_lat', models.FloatField(blank=True, null=True)),
                ('current_lon', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('standby', 'Standby'), ('offline', 'Offline')], default='standby', max_length=20)),
                ('last_ping', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_units', to='api.county')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_units', to='api.incident')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EarlyWarningBroadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('email', 'Email')], default='sms', max_length=20)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('recipient_count', models.IntegerField(default=0)),
                ('delivered_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('provider_response', models.JSONField(blank=True, default=dict)),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcasts', to='api.floodalert')),
                ('counties', models.ManyToManyField(related_name='broadcasts', to='api.county')),
                ('sent_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcasts', to='api.incident')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnnotatedZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('zone_type', models.CharField(choices=[('evacuation_route', 'Evacuation Route'), ('staging_area', 'Staging Area'), ('cordon', 'Cordon Zone'), ('flood_extent', 'Estimated Flood Extent'), ('safe_zone', 'Safe Zone')], max_length=30)),
                ('geojson_geometry', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotated_zones', to='api.county')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annotated_zones', to='api.incident')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IncidentUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_system', models.BooleanField(default=False)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='api.incident')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SocialIntelItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('twitter', 'Twitter/X'), ('facebook', 'Facebook'), ('news_rss', 'News RSS'), ('radio', 'Radio Transcript'), ('manual', 'Manual Entry')], default='news_rss', max_length=20)),
                ('url', models.URLField(blank=True, max_length=500)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('snippet', models.TextField()),
                ('sentiment', models.CharField(choices=[('urgent', 'Urgent'), ('negative', 'Negative'), ('neutral', 'Neutral'), ('positive', 'Positive')], default='neutral', max_length=20)),
                ('extracted_lat', models.FloatField(blank=True, null=True)),
                ('extracted_lon', models.FloatField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('flag', models.CharField(choices=[('unreviewed', 'Unreviewed'), ('verified', 'Verified'), ('false', 'False/Irrelevant'), ('escalated', 'Escalated')], default='unreviewed', max_length=20)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('source_published_at', models.DateTimeField(blank=True, null=True)),
                ('content_hash', models.CharField(max_length=64, unique=True)),
                ('county', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intel_items', to='api.county')),
                ('flagged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-ingested_at'],
            },
        ),
        migrations.CreateModel(
            name='WeatherObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.CharField(max_length=50)),
                ('station_name', models.CharField(blank=True, max_length=100)),
                ('rainfall_mm', models.FloatField(default=0)),
                ('temperature_c', models.FloatField(blank=True, null=True)),
                ('humidity_pct', models.FloatField(blank=True, null=True)),
                ('wind_speed_kmh', models.FloatField(blank=True, null=True)),
                ('river_level_cm', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(default='kmd', max_length=50)),
                ('observed_at', models.DateTimeField()),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_observations', to='api.county')),
            ],
            options={
                'ordering': ['-observed_at'],
            },
        ),
        migrations.CreateModel(
            name='FieldUnitPing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('speed_kmh', models.FloatField(default=0)),
                ('heading', models.FloatField(default=0)),
                ('battery_pct', models.IntegerField(default=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pings', to='api.fieldunit')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['unit', 'timestamp'], name='api_fieldun_unit_id_cfbcb5_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['status', 'severity', 'county'], name='api_inciden_status_5684d3_idx'),
        ),
        migrations.AddIndex(
            model_name='socialintelitem',
            index=models.Index(fields=['county', 'sentiment', 'ingested_at'], name='api_sociali_county__6ffa74_idx'),
        ),
        migrations.AddIndex(
            model_name='weatherobservation',
            index=models.Index(fields=['county', 'station_id', 'observed_at'], name='api_weather_county__be8ee5_idx'),
        ),
    ]
