# Generated by Django 5.0.3 on 2026-03-18 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_apikey_alertsubscription'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='broadcastrecipient',
            constraint=models.UniqueConstraint(condition=models.Q(('phone__gt', '')), fields=('phone', 'channel'), name='unique_recipient_phone_channel'),
        ),
        migrations.AddConstraint(
            model_name='broadcastrecipient',
            constraint=models.UniqueConstraint(condition=models.Q(('email__gt', '')), fields=('email', 'channel'), name='unique_recipient_email_channel'),
        ),
    ]
