# Generated by Django 5.0.3 on 2026-03-18 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_unique_recipient_phone_email_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='camerafeed',
            name='agency',
            field=models.CharField(blank=True, default='Other', max_length=50),
        ),
        migrations.AddField(
            model_name='camerafeed',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
