# Generated by Django 5.0.3 on 2026-03-18 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_camera_agency_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('field_unit', 'Field Unit'), ('camera', 'Camera Feed')], max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incident_assignments', to='api.camerafeed')),
                ('field_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incident_assignments', to='api.fieldunit')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='api.incident')),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='incidentresource',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('resource_type', 'field_unit'), ('field_unit__isnull', False), ('camera__isnull', True)), models.Q(('resource_type', 'camera'), ('camera__isnull', False), ('field_unit__isnull', True)), _connector='OR'), name='valid_incident_resource'),
        ),
    ]
