# Generated by Django 5.0.3 on 2026-03-18 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_incidentresource_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastDeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='sent', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('broadcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_logs', to='api.earlywarningbroadcast')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.broadcastrecipient')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['broadcast', 'status'], name='api_broadca_broadca_50a8df_idx')],
            },
        ),
    ]
